name: Publish KMMBridge

on:
  workflow_dispatch:

env:
  MAVEN_USERNAME: ${{ secrets.REPSY_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.REPSY_PASSWORD }}

jobs:
  kmm-publish:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.6.1
        with:
          gradle-home-cache-cleanup: true

      - name: Build
        run:
          ./gradlew  -PENABLE_PUBLISHING=true -PGITHUB_PUBLISH_TOKEN=${{ secrets.GITHUB_TOKEN }} -PGITHUB_REPO=${{ github.repository }} kmmBridgePublish

